name: Build KickMe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact: kickme-linux
            add_binary: 'zig-out/lib/libdsp.so:.'
          - os: windows-latest
            artifact: kickme-windows
            add_binary: 'zig-out/bin/dsp.dll;.'
          - os: macos-latest
            artifact: kickme-macos
            add_binary: 'zig-out/lib/libdsp.dylib:.'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.17.0-dev.644+3de725074 # if it breaks, it's probably this
                                            # update to a newer version and pin to 0.17 when released stable
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 pyinstaller

      - name: Build DSP (Zig)
        run: zig build -Doptimize=ReleaseFast

      - name: Bundle with PyInstaller
        run: pyinstaller --noconfirm --windowed --onefile --name kickme --add-binary "${{ matrix.add_binary }}" gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            dist/kickme
            dist/kickme.exe
            dist/kickme.app
          if-no-files-found: ignore
